# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'
  apiProject: 'ECom/ECom.API/ECom.API.csproj'

steps:
- script: dotnet restore $(apiProject)
  displayName: 'dotnet restore'
- script: dotnet build  $(apiProject) --configuration $(buildConfiguration)
  displayName: 'dotnet build'
- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: publish 
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True
- task: PublishBuildArtifacts@1
  displayName: 'publish artifacts'